In [101]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [102]:
# Importing file and reading it as dataframe
df=pd.read_csv("E:/Pracitce_project_codes/Natural_Language_Processing/gensim_topic_modelling/TopicModeling/loanP_train_DS_PY.csv")

In [103]:
# Lets see the first 5 rows of the dataframe
df.head(10)

Loan_ID Gender Marital_Status Dependents Graduate Self_Employed  \
0  LI0100   Male         Single          0      Yes            No   
1  LI0101   Male        Married          1      Yes            No   
2  LI0102   Male        Married          0      Yes           Yes   
3  LI0103   Male        Married          0       No            No   
4  LI0104   Male         Single          0      Yes            No   
5  LI0105   Male        Married          2      Yes           Yes   
6  LI0106   Male        Married          0       No            No   
7  LI0107   Male        Married         3+      Yes            No   
8  LI0108   Male        Married          2      Yes            No   
9  LI0109   Male        Married          1      Yes            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [104]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       599.000000         599.000000  578.000000        585.000000   
mean       5420.687813        1563.913055  145.434256        342.461538   
std        6169.168633        2456.618360   84.596463         64.868352   
min         150.000000           0.000000    9.000000         12.000000   
25%        2874.000000           0.000000  100.000000        360.000000   
50%        3812.000000        1210.000000  126.500000        360.000000   
75%        5807.500000        2279.000000  165.000000        360.000000   
max       81000.000000       33837.000000  700.000000        480.000000   

       Credit_History  
count       550.00000  
mean          0.84000  
std           0.36694  
min           0.00000  
25%           1.00000  
50%           1.00000  
75%           1.00000  
max           1.00000

In [105]:
#Now lets talk about the dataset colum wise
LoadID : it has all unique entities which doesnt help for machine learning modeling so we can safely remove it 
Gender  : It is categorical in nature so we will convert it into numerical using encoding 
Marital status : categorical so it will be coverted into the numerical using encoding
Dependents : it is already in numerical form
Graduate : categorical so it will be converted into numerical 
Self employed : categorical will be converted into numerical 
ApplicantIncome : it is already numerical but it has very high values so it should be normalized
CoApplicantIncome : it is already numerical but it has very high values so it should be normalized
LoanAmount : it has all numerical values so it should be normalized and some are missing like NaN so these should be replaced by mean of other values 
Loan_Amount_Term : It should be normalized
Credit_History : it is already sorted
Property_Area : this should be encoded
Loan_Status : it should be encoded too



SyntaxError: invalid syntax (<ipython-input-105-2a129f701e1c>, line 2)

In [106]:
# Now lets find columns with missing values 
ColumnsWith_NaN={}
for i in df.columns:
    if df[i].isnull().any().any():
        
        ColumnsWith_NaN[i]=df[i].isnull().sum().sum()
print(ColumnsWith_NaN)

{'Gender': 13, 'Marital_Status': 3, 'Dependents': 15, 'Self_Employed': 30, 'LoanAmount': 21, 'Loan_Amount_Term': 14, 'Credit_History': 49}


In [107]:
# There are so many missing values so to deal with them all we will be using different techniques 
#There are many ways to impute missing values. These are a few of them
#1. Deletion
#2. Mean/ Mode/ Median Imputation
#3. Prediction Model Imputation
#4. KNN Imputation

In [108]:
# Lets start with gender here NaN can be filled in two ways either replace them with high entity since count of male is high 
# we can replace NaN with male or we can find see the column of income and replace them 
df.Gender.describe()

count      586
unique       2
top       Male
freq       478
Name: Gender, dtype: object

In [109]:
# since Male are more than woman so we can replace NaN by Male
df['Gender'].fillna('Male',inplace=True)

In [110]:
# Lets check if there any NAN present
df['Gender'].isnull().sum()

0

In [111]:
# Lets fill the Marital_status by same technique
df.Marital_Status.describe()

count         596
unique          2
top       Married
freq          387
Name: Marital_Status, dtype: object

In [112]:
# since most of the candidates are Married so replace NAN with Married
df.Marital_Status.fillna('Married',inplace=True)

In [113]:
# Lets check if there any NaN present in Marital_Status columnn (if results 0 it means there is no NAN)
df.Marital_Status.isnull().sum()

0

In [114]:
# Lets fill the Dependents column since its a numerical column
df.Dependents.describe()


count     584
unique      4
top         0
freq      339
Name: Dependents, dtype: object

In [115]:
# in this column either we can use replace NaN with 0 (highest occuring) or we can NaN by taking mean of non NaN values
df.Dependents.fillna('0',inplace=True)

In [116]:
list1=[]
df.Dependents.isnull().sum()
list1=df.Dependents.values
list1=list(list1)
print(set(list1))

{'0', '3+', '2', '1'}


In [117]:
# Check if there is any NAN
df.Dependents.isnull().sum()

0

In [118]:
df.Self_Employed.describe()

count     569
unique      2
top        No
freq      488
Name: Self_Employed, dtype: object

In [119]:
# Since in Self_Employed column most of the entities are "No" so we will replace NaN with No
df.Self_Employed.fillna("No",inplace=True)

In [120]:
# Lets check for NaN in Self_Employed column
df.Self_Employed.isnull().sum()

0

In [121]:
# Next column is LoanAmount with 21 NaN. 
df.LoanAmount.describe()
df.LoanAmount.isnull().sum()


21

In [122]:
#type(df.LoanAmount.mean())
#Since it is a numerical column we will replace the NaN value with mean value 
df.LoanAmount.fillna(df.LoanAmount.mean(),inplace=True)


In [123]:
#check if all NaN filled with mean Value
df.LoanAmount.isnull().sum()

0

In [124]:
# Next column is Loan_Amount_Term lets describe it 
df.Loan_Amount_Term.describe()
df.Loan_Amount_Term.isnull().sum()

14

In [125]:
#Since it is a numerical column we will replace the NaN value with mean value 
df.Loan_Amount_Term.fillna(df.LoanAmount.mean(),inplace=True)

In [126]:
# Lets check if there any NaN present
df.Loan_Amount_Term.isnull().sum()

0

In [127]:
# Lets fill NaN in column Credit_History first lets describe it 
df.Credit_History.describe()

count    550.00000
mean       0.84000
std        0.36694
min        0.00000
25%        1.00000
50%        1.00000
75%        1.00000
max        1.00000
Name: Credit_History, dtype: float64

In [128]:
#Since it is a numerical column we will replace the NaN value with mean value 
df.Credit_History.fillna(df.LoanAmount.mean(),inplace=True)

In [129]:
# Lets check if there any NaN present
df.Credit_History.isnull().sum()

0

In [130]:
## Till here we have filled all the NaN values in the dataset with one of the appropriate method now we can check if there
## any NAN present in the dataset
df.isnull().sum()

Loan_ID              0
Gender               0
Marital_Status       0
Dependents           0
Graduate             0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [131]:
## So there is not any NaN in the dataset now we can proceed to the next step of preprocessing the data 
## Next step is encoding the categorical values 


In [132]:
# First have a look at dataframe without applying encoding 
df.head()

Loan_ID Gender Marital_Status Dependents Graduate Self_Employed  \
0  LI0100   Male         Single          0      Yes            No   
1  LI0101   Male        Married          1      Yes            No   
2  LI0102   Male        Married          0      Yes           Yes   
3  LI0103   Male        Married          0       No            No   
4  LI0104   Male         Single          0      Yes            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  145.434256             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [149]:
# Now lets apply label encoding on columns with categorical values 
encoded=df[['Self_Employed','Dependents','Gender','Marital_Status','Graduate','Property_Area','Loan_Status']].apply(LabelEncoder().fit_transform)

In [ ]:
encoded

In [135]:
df

Loan_ID Gender Marital_Status Dependents Graduate Self_Employed  \
0  LI0100   Male         Single          0      Yes            No   
1  LI0101   Male        Married          1      Yes            No   
2  LI0102   Male        Married          0      Yes           Yes   
3  LI0103   Male        Married          0       No            No   
4  LI0104   Male         Single          0      Yes            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  145.434256             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [150]:
remain=df[['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History']]

In [161]:
encoded.head()

Self_Employed  Dependents  Gender  Marital_Status  Graduate  Property_Area  \
0              0           0       1               1         1              2   
1              0           1       1               0         1              0   
2              1           0       1               0         1              2   
3              0           0       1               0         0              2   
4              0           0       1               1         1              2   

   Loan_Status  
0            1  
1            0  
2            1  
3            1  
4            1

In [171]:
# Adding both the dataframes encoded and remaining (without encoding)
#final=remain+encoded
bigdata =pd.concat([remain, encoded], axis=1)

In [172]:
bigdata.columns

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Self_Employed', 'Dependents',
       'Gender', 'Marital_Status', 'Graduate', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [175]:
bigdata.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  145.434256             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Self_Employed  Dependents  Gender  Marital_Status  \
0             1.0              0           0       1               1   
1             1.0              0           1       1               0   
2             1.0              1           0       1               0   
3             1.0              0           0       1               0   
4             1.0              0           0       1               1   

   Graduate  Property_Area  Loan_Status  
0         1              2            1  
1         1              0            0  
2         1              2            1  
3         0              2            1  
4         1              2            1

In [189]:
bigdata.columns

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Self_Employed', 'Dependents',
       'Gender', 'Marital_Status', 'Graduate', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [181]:
## Now our dataframe named bigdata is ready to use it for train the model 


In [191]:
X=bigdata[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Self_Employed', 'Dependents',
       'Gender', 'Marital_Status', 'Graduate', 'Property_Area']]
y=bigdata['Loan_Status']


In [192]:
# Since machine learning algorithms consumes only data in array format so converting our dataframe into numpy arrays
X=X.values
y=y.values

In [194]:
# Lets split the data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [195]:
print(x_train.shape,x_test.shape)

(479, 11) (120, 11)


In [209]:
# Now Appling different machine learning algorithm on this data and see thier performance

from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
svm_clf= svm.SVC(gamma='scale', random_state=0)
nb_clf=GaussianNB()
lr_clf=LogisticRegression()
dt_clf=DecisionTreeClassifier()


In [210]:
# Fitting training data to different classifier
lr_clf.fit(x_train,y_train)
svm_clf.fit(x_train,y_train)
dt_clf.fit(x_train,y_train)
nb_clf.fit(x_train,y_train)

C:\Users\piyushs\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


GaussianNB(priors=None, var_smoothing=1e-09)

In [214]:
from sklearn.model_selection import cross_val_score
models=[lr_clf,svm_clf,dt_clf,nb_clf]
for i in models:
    print(cross_val_score(i,x_train, y_train, scoring='accuracy',cv=5))

C:\Users\piyushs\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\piyushs\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\piyushs\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\piyushs\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\piyushs\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

[0.65979381 0.67708333 0.66666667 0.67368421 0.64210526]
[0.68041237 0.60416667 0.63541667 0.67368421 0.67368421]
[0.63917526 0.71875    0.70833333 0.71578947 0.72631579]
[0.62886598 0.625      0.60416667 0.61052632 0.61052632]


In [215]:
# Here it is clearly seen that for 5 different sets decision tree is trained well on the data
# Now lets score on test data
dt_clf.score(x_test, y_test) 

0.7166666666666667

In [ ]:
# So our model is predicting with 71 percent accuracy 
This accuracy can be increased by applying more technique on the data preprocessing part